<?php

/**
 * This is the model base class for the table "Acteurs_has_Films".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ActeursHasFilms".
 *
 * Columns in table "Acteurs_has_Films" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Acteurs_idActeurs
 * @property integer $Films_idFilms
 *
 */
abstract class BaseActeursHasFilms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Acteurs_has_Films';
	}

	public static function representingColumn() {
		return array(
			'Acteurs_idActeurs',
			'Films_idFilms',
		);
	}

	public function rules() {
		return array(
			array('Acteurs_idActeurs, Films_idFilms', 'required'),
			array('Acteurs_idActeurs, Films_idFilms', 'numerical', 'integerOnly'=>true),
			array('Acteurs_idActeurs, Films_idFilms', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Acteurs_idActeurs' => Yii::t('app', 'Acteurs Id Acteurs'),
			'Films_idFilms' => Yii::t('app', 'Films Id Films'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Acteurs_idActeurs', $this->Acteurs_idActeurs);
		$criteria->compare('Films_idFilms', $this->Films_idFilms);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}