<?php

/**
 * This is the model base class for the table "Langues_has_Films_Telechargements".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LanguesHasFilmsTelechargements".
 *
 * Columns in table "Langues_has_Films_Telechargements" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Langues_idLangues
 * @property integer $Films_Telechargements_idFilms_Telechargements
 *
 */
abstract class BaseLanguesHasFilmsTelechargements extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Langues_has_Films_Telechargements';
	}

	public static function representingColumn() {
		return array(
			'Langues_idLangues',
			'Films_Telechargements_idFilms_Telechargements',
		);
	}

	public function rules() {
		return array(
			array('Langues_idLangues, Films_Telechargements_idFilms_Telechargements', 'required'),
			array('Langues_idLangues, Films_Telechargements_idFilms_Telechargements', 'numerical', 'integerOnly'=>true),
			array('Langues_idLangues, Films_Telechargements_idFilms_Telechargements', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Langues_idLangues' => Yii::t('app', 'Langues Id Langues'),
			'Films_Telechargements_idFilms_Telechargements' => Yii::t('app', 'Films Telechargements Id Films Telechargements'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Langues_idLangues', $this->Langues_idLangues);
		$criteria->compare('Films_Telechargements_idFilms_Telechargements', $this->Films_Telechargements_idFilms_Telechargements);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}