<?php

/**
 * This is the model base class for the table "Realisateurs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Realisateurs".
 *
 * Columns in table "Realisateurs" available as properties of the model,
 * followed by relations of table "Realisateurs" available as properties of the model.
 *
 * @property integer $idRealisateurs
 * @property string $RealisateurNom
 *
 * @property Films[] $films
 */
abstract class BaseRealisateurs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Realisateurs';
	}

	public static function representingColumn() {
		return 'RealisateurNom';
	}

	public function rules() {
		return array(
			array('RealisateurNom', 'required'),
			array('RealisateurNom', 'length', 'max'=>45),
			array('idRealisateurs, RealisateurNom', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'films' => array(self::MANY_MANY, 'Films', 'Realisateurs_has_Films(Realisateurs_idRealisateurs, Films_idFilms)'),
		);
	}

	public function pivotModels() {
		return array(
			'films' => 'RealisateursHasFilms',
		);
	}

	public function attributeLabels() {
		return array(
			'idRealisateurs' => Yii::t('app', 'Id Realisateurs'),
			'RealisateurNom' => Yii::t('app', 'Realisateur Nom'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idRealisateurs', $this->idRealisateurs);
		$criteria->compare('RealisateurNom', $this->RealisateurNom, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}