<?php

/**
 * This is the model base class for the table "Langues".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Langues".
 *
 * Columns in table "Langues" available as properties of the model,
 * followed by relations of table "Langues" available as properties of the model.
 *
 * @property integer $idLangues
 * @property string $LanguesNom
 *
 * @property FilmsTelechargements[] $filmsTelechargements
 */
abstract class BaseLangues extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Langues';
	}

	public static function representingColumn() {
		return 'LanguesNom';
	}

	public function rules() {
		return array(
			array('LanguesNom', 'required'),
			array('LanguesNom', 'length', 'max'=>50),
			array('idLangues, LanguesNom', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'filmsTelechargements' => array(self::MANY_MANY, 'FilmsTelechargements', 'Langues_has_Films_Telechargements(Langues_idLangues, Films_Telechargements_idFilms_Telechargements)'),
		);
	}

	public function pivotModels() {
		return array(
			'filmsTelechargements' => 'LanguesHasFilmsTelechargements',
		);
	}

	public function attributeLabels() {
		return array(
			'idLangues' => Yii::t('app', 'Id Langues'),
			'LanguesNom' => Yii::t('app', 'Langues Nom'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idLangues', $this->idLangues);
		$criteria->compare('LanguesNom', $this->LanguesNom, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}