<?php

/**
 * This is the model base class for the table "Hebergeures".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Hebergeures".
 *
 * Columns in table "Hebergeures" available as properties of the model,
 * followed by relations of table "Hebergeures" available as properties of the model.
 *
 * @property integer $idHebergeures
 * @property string $HebergeursNom
 * @property string $HebergeuresTag
 *
 * @property FilmsTelechargements[] $filmsTelechargements
 */
abstract class BaseHebergeures extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Hebergeures';
	}

	public static function representingColumn() {
		return 'HebergeursNom';
	}

	public function rules() {
		return array(
			array('HebergeursNom, HebergeuresTag', 'required'),
			array('HebergeursNom', 'length', 'max'=>75),
			array('HebergeuresTag', 'length', 'max'=>45),
			array('idHebergeures, HebergeursNom, HebergeuresTag', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'filmsTelechargements' => array(self::MANY_MANY, 'FilmsTelechargements', 'Hebergeures_has_Films_Telechargements(Hebergeures_idHebergeures, Films_Telechargements_idFilms_Telechargements)'),
		);
	}

	public function pivotModels() {
		return array(
			'filmsTelechargements' => 'HebergeuresHasFilmsTelechargements',
		);
	}

	public function attributeLabels() {
		return array(
			'idHebergeures' => Yii::t('app', 'Id Hebergeures'),
			'HebergeursNom' => Yii::t('app', 'Hebergeurs Nom'),
			'HebergeuresTag' => Yii::t('app', 'Hebergeures Tag'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idHebergeures', $this->idHebergeures);
		$criteria->compare('HebergeursNom', $this->HebergeursNom, true);
		$criteria->compare('HebergeuresTag', $this->HebergeuresTag, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}