<?php

/**
 * This is the model base class for the table "Pays_has_Films".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PaysHasFilms".
 *
 * Columns in table "Pays_has_Films" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Pays_idPays
 * @property integer $Films_idFilms
 *
 */
abstract class BasePaysHasFilms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Pays_has_Films';
	}

	public static function representingColumn() {
		return array(
			'Pays_idPays',
			'Films_idFilms',
		);
	}

	public function rules() {
		return array(
			array('Pays_idPays, Films_idFilms', 'required'),
			array('Pays_idPays, Films_idFilms', 'numerical', 'integerOnly'=>true),
			array('Pays_idPays, Films_idFilms', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Pays_idPays' => Yii::t('app', 'Pays Id Pays'),
			'Films_idFilms' => Yii::t('app', 'Films Id Films'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Pays_idPays', $this->Pays_idPays);
		$criteria->compare('Films_idFilms', $this->Films_idFilms);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}