<?php

/**
 * This is the model base class for the table "sous_titre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SousTitre".
 *
 * Columns in table "sous_titre" available as properties of the model,
 * followed by relations of table "sous_titre" available as properties of the model.
 *
 * @property integer $idsous_titre
 * @property string $sous_titreNom
 *
 * @property FilmsTelechargements[] $filmsTelechargements
 */
abstract class BaseSousTitre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sous_titre';
	}

	public static function representingColumn() {
		return 'sous_titreNom';
	}

	public function rules() {
		return array(
			array('sous_titreNom', 'required'),
			array('sous_titreNom', 'length', 'max'=>45),
			array('idsous_titre, sous_titreNom', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'filmsTelechargements' => array(self::MANY_MANY, 'FilmsTelechargements', 'sous_titre_has_Films_Telechargements(sous_titre_idsous_titre, Films_Telechargements_idFilms_Telechargements)'),
		);
	}

	public function pivotModels() {
		return array(
			'filmsTelechargements' => 'SousTitreHasFilmsTelechargements',
		);
	}

	public function attributeLabels() {
		return array(
			'idsous_titre' => Yii::t('app', 'Idsous Titre'),
			'sous_titreNom' => Yii::t('app', 'Sous Titre Nom'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idsous_titre', $this->idsous_titre);
		$criteria->compare('sous_titreNom', $this->sous_titreNom, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}