<?php

/**
 * This is the model base class for the table "Acteurs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Acteurs".
 *
 * Columns in table "Acteurs" available as properties of the model,
 * followed by relations of table "Acteurs" available as properties of the model.
 *
 * @property integer $idActeurs
 * @property string $ActeursNom
 *
 * @property Films[] $films
 */
abstract class BaseActeurs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Acteurs';
	}

	public static function representingColumn() {
		return 'ActeursNom';
	}

	public function rules() {
		return array(
			array('ActeursNom', 'required'),
			array('ActeursNom', 'length', 'max'=>45),
			array('idActeurs, ActeursNom', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'films' => array(self::MANY_MANY, 'Films', 'Acteurs_has_Films(Acteurs_idActeurs, Films_idFilms)'),
		);
	}

	public function pivotModels() {
		return array(
			'films' => 'ActeursHasFilms',
		);
	}

	public function attributeLabels() {
		return array(
			'idActeurs' => Yii::t('app', 'Id Acteurs'),
			'ActeursNom' => Yii::t('app', 'Acteurs Nom'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idActeurs', $this->idActeurs);
		$criteria->compare('ActeursNom', $this->ActeursNom, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}