<?php

/**
 * This is the model base class for the table "Genres_has_Films".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GenresHasFilms".
 *
 * Columns in table "Genres_has_Films" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Genres_idGenres
 * @property integer $Films_idFilms
 *
 */
abstract class BaseGenresHasFilms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Genres_has_Films';
	}

	public static function representingColumn() {
		return array(
			'Genres_idGenres',
			'Films_idFilms',
		);
	}

	public function rules() {
		return array(
			array('Genres_idGenres, Films_idFilms', 'required'),
			array('Genres_idGenres, Films_idFilms', 'numerical', 'integerOnly'=>true),
			array('Genres_idGenres, Films_idFilms', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Genres_idGenres' => Yii::t('app', 'Genres Id Genres'),
			'Films_idFilms' => Yii::t('app', 'Films Id Films'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Genres_idGenres', $this->Genres_idGenres);
		$criteria->compare('Films_idFilms', $this->Films_idFilms);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}