<?php

/**
 * This is the model base class for the table "Qualiter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Qualiter".
 *
 * Columns in table "Qualiter" available as properties of the model,
 * followed by relations of table "Qualiter" available as properties of the model.
 *
 * @property integer $idQualiter
 * @property string $QualiterNom
 * @property string $QualiterDescription
 *
 * @property FilmsTelechargements[] $filmsTelechargements
 */
abstract class BaseQualiter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Qualiter';
	}

	public static function representingColumn() {
		return 'QualiterNom';
	}

	public function rules() {
		return array(
			array('QualiterNom', 'required'),
			array('QualiterNom', 'length', 'max'=>45),
			array('QualiterDescription', 'safe'),
			array('QualiterDescription', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idQualiter, QualiterNom, QualiterDescription', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'filmsTelechargements' => array(self::MANY_MANY, 'FilmsTelechargements', 'Qualiter_has_Films_Telechargements(Qualiter_idQualiter, Films_Telechargements_idFilms_Telechargements)'),
		);
	}

	public function pivotModels() {
		return array(
			'filmsTelechargements' => 'QualiterHasFilmsTelechargements',
		);
	}

	public function attributeLabels() {
		return array(
			'idQualiter' => Yii::t('app', 'Id Qualiter'),
			'QualiterNom' => Yii::t('app', 'Qualiter Nom'),
			'QualiterDescription' => Yii::t('app', 'Qualiter Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idQualiter', $this->idQualiter);
		$criteria->compare('QualiterNom', $this->QualiterNom, true);
		$criteria->compare('QualiterDescription', $this->QualiterDescription, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}