<?php

/**
 * This is the model base class for the table "Realisateurs_has_Films".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RealisateursHasFilms".
 *
 * Columns in table "Realisateurs_has_Films" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Realisateurs_idRealisateurs
 * @property integer $Films_idFilms
 *
 */
abstract class BaseRealisateursHasFilms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Realisateurs_has_Films';
	}

	public static function representingColumn() {
		return array(
			'Realisateurs_idRealisateurs',
			'Films_idFilms',
		);
	}

	public function rules() {
		return array(
			array('Realisateurs_idRealisateurs, Films_idFilms', 'required'),
			array('Realisateurs_idRealisateurs, Films_idFilms', 'numerical', 'integerOnly'=>true),
			array('Realisateurs_idRealisateurs, Films_idFilms', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Realisateurs_idRealisateurs' => Yii::t('app', 'Realisateurs Id Realisateurs'),
			'Films_idFilms' => Yii::t('app', 'Films Id Films'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Realisateurs_idRealisateurs', $this->Realisateurs_idRealisateurs);
		$criteria->compare('Films_idFilms', $this->Films_idFilms);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}