<?php

/**
 * This is the model base class for the table "Qualiter_has_Films_Telechargements".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QualiterHasFilmsTelechargements".
 *
 * Columns in table "Qualiter_has_Films_Telechargements" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Qualiter_idQualiter
 * @property integer $Films_Telechargements_idFilms_Telechargements
 *
 */
abstract class BaseQualiterHasFilmsTelechargements extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Qualiter_has_Films_Telechargements';
	}

	public static function representingColumn() {
		return array(
			'Qualiter_idQualiter',
			'Films_Telechargements_idFilms_Telechargements',
		);
	}

	public function rules() {
		return array(
			array('Qualiter_idQualiter, Films_Telechargements_idFilms_Telechargements', 'required'),
			array('Qualiter_idQualiter, Films_Telechargements_idFilms_Telechargements', 'numerical', 'integerOnly'=>true),
			array('Qualiter_idQualiter, Films_Telechargements_idFilms_Telechargements', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Qualiter_idQualiter' => Yii::t('app', 'Qualiter Id Qualiter'),
			'Films_Telechargements_idFilms_Telechargements' => Yii::t('app', 'Films Telechargements Id Films Telechargements'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Qualiter_idQualiter', $this->Qualiter_idQualiter);
		$criteria->compare('Films_Telechargements_idFilms_Telechargements', $this->Films_Telechargements_idFilms_Telechargements);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}