<?php

/**
 * This is the model base class for the table "Genres".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Genres".
 *
 * Columns in table "Genres" available as properties of the model,
 * followed by relations of table "Genres" available as properties of the model.
 *
 * @property integer $idGenres
 * @property string $GenresTitre
 *
 * @property Films[] $films
 */
abstract class BaseGenres extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Genres';
	}

	public static function representingColumn() {
		return 'GenresTitre';
	}

	public function rules() {
		return array(
			array('GenresTitre', 'required'),
			array('GenresTitre', 'length', 'max'=>45),
			array('idGenres, GenresTitre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'films' => array(self::MANY_MANY, 'Films', 'Genres_has_Films(Genres_idGenres, Films_idFilms)'),
		);
	}

	public function pivotModels() {
		return array(
			'films' => 'GenresHasFilms',
		);
	}

	public function attributeLabels() {
		return array(
			'idGenres' => Yii::t('app', 'Id Genres'),
			'GenresTitre' => Yii::t('app', 'Genres Titre'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idGenres', $this->idGenres);
		$criteria->compare('GenresTitre', $this->GenresTitre, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}